#!/bin/bash

# Bash script to make ws.jar executable from anywhere. Just make this script executable, add the path to the jar,
# add the path to the default words file, and place the directory with the jar on your PATH.

if [ $# -eq 0]; then
    java -jar /<path>/<to>/ws.jar /<path>/<to>/<default>/<words>
else
    java -jar /<path>/<to>/ws.jar $1
fi